# Generated by Django 5.0.7 on 2024-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
        ('usuarios', '0004_customuser_posgrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='posgrado',
        ),
        migrations.AddField(
            model_name='customuser',
            name='posgrado',
            field=models.ManyToManyField(blank=True, to='generales.posgrado', verbose_name='Posgrado'),
        ),
    ]
