# Generated by Django 5.0.7 on 2024-09-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
        ('usuarios', '0005_remove_customuser_posgrado_customuser_posgrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='posgrado',
        ),
        migrations.AddField(
            model_name='customuser',
            name='posgrado_alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='generales.posgrado', verbose_name='Posgrado Alumno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='posgrado_docente',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='generales.posgrado', verbose_name='Posgrado Docente'),
        ),
    ]
