# Generated by Django 5.0.7 on 2024-09-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
        ('usuarios', '0006_remove_customuser_posgrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posgrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to='generales.posgrado', verbose_name='Posgrado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Coordinador')),
            ],
        ),
    ]
