# Generated by Django 5.0.7 on 2024-09-23 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_coordinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutoría de Alumno',
                'verbose_name_plural': 'Tutorías de Alumnos',
                'unique_together': {('tutor', 'alumno')},
            },
        ),
    ]
